In [2]:
from LOTUS_regression.predictors import load_data
import numpy as np
import pandas as pd


In [47]:

predictors = load_data('pred_baseline_ilt.csv')
predictors[0:10]
# list(predictors)
# predictors.index()
predictors[-10:]

enso      trop     solar      qboA      qboB       aod  \
time                                                                     
2016-09-01 -0.186635 -2.338428 -0.713954  0.972447 -0.829060 -0.476721   
2016-10-01 -0.467222 -2.065989 -0.770345  0.987041 -0.845240 -0.476721   
2016-11-01 -0.298668 -1.694497 -0.949032  1.045864 -0.957971 -0.476721   
2016-12-01 -0.206821 -0.938390 -1.028524  1.087502 -1.096618 -0.476721   
2017-01-01 -0.140207  0.011418 -0.988438  0.924099 -1.166034 -0.476721   
2017-02-01 -0.141216  0.222267 -0.984588  0.972497 -1.215657 -0.476721   
2017-03-01 -0.165439  0.823427 -1.007915  0.617551 -1.299313 -0.476721   
2017-04-01  0.692472  0.615894 -0.855046 -0.073552 -1.392675 -0.476721   
2017-05-01  1.383848 -0.009627 -0.981418 -0.839010 -1.087476 -0.476721   
2017-06-01  0.974069  0.091761 -0.942012 -1.240147 -0.550501 -0.476721   

            linear_pre  linear_post  pre_const  post_const  gap_cons  
time                                                                  
2016-09-01        -0.0     1.666838        0.0         1.0       0.0  
2016-10-01        -0.0     1.675052        0.0         1.0       0.0  
2016-11-01        -0.0     1.683539        0.0         1.0       0.0  
2016-12-01        -0.0     1.691753        0.0         1.0       0.0  
2017-01-01        -0.0     1.700240        0.0         1.0       0.0  
2017-02-01        -0.0     1.708728        0.0         1.0       0.0  
2017-03-01        -0.0     1.716394        0.0         1.0       0.0  
2017-04-01        -0.0     1.724881        0.0         1.0       0.0  
2017-05-01        -0.0     1.733095        0.0         1.0       0.0  
2017-06-01        -0.0     1.741583        0.0         1.0       0.0

In [5]:
np.mean(predictors['aod']), np.std(predictors['aod'])

(0.006183351742546824, 1.130967806403387)

In [48]:
np.mean(predictors['solar']), np.std(predictors['solar'])

(0.02838617921957625, 0.9795363075908319)

In [6]:
np.mean(predictors['linear_post']), np.std(predictors['linear_post'])

(0.37703350457248125, 0.5446623412041101)

In [11]:
for i in range(len(predictors)):
    if(predictors.iloc[i]['linear_post'] == 0):print(predictors.iloc[i].time)

AttributeError: 'Series' object has no attribute 'time'

In [27]:
pred = pd.read_csv('/home/poyraden/Analysis/MLR_Uccle/Files/Extended_ilt.csv')
pred.rename(columns={'Unnamed: 0': 'date'}, inplace=True)
pred[0:3]

# pred['date'] = pd.to_datetime(pred['date'], format='%Y-%m-%d')
pred.set_index('date', inplace=True)
pred.index

Index(['1969-01', '1969-02', '1969-03', '1969-04', '1969-05', '1969-06',
       '1969-07', '1969-08', '1969-09', '1969-10',
       ...
       '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08',
       '2018-09', '2018-10', '2018-11', '2018-12'],
      dtype='object', name='date', length=600)

In [34]:
pred[0:3]


linear_pre  linear_post  post_const  pre_const  gap_const   enso  \
date                                                                        
1969-01   -2.800057          0.0         0.0        1.0        0.0  0.670   
1969-02   -2.791570          0.0         0.0        1.0        0.0  0.849   
1969-03   -2.783904          0.0         0.0        1.0        0.0  0.458   

             qboA      qboB     solar       AOD  
date                                             
1969-01  1.259361  0.897587  0.594145  1.240826  
1969-02  1.132396  0.537626  0.672909  1.176370  
1969-03  1.322247  0.249722  1.087912  1.108205

In [36]:
np.mean(pred['AOD']), np.std(pred['AOD'])

(3.55474908767898e-15, 0.9999999999999976)

In [65]:
np.mean(pred['enso']), np.std(pred['enso'])

(0.21760666666666675, 0.995573612859553)

In [66]:
np.mean(pred['solar']), np.std(pred['solar'])

(-9.38508530149799e-16, 0.9999999999999994)

In [54]:
predp = pred.loc['1969-01-01':'1996-12-01']
predg = pred.loc['1997-01-01':'1999-12-01']
predpo = pred.loc['2000-01-01':'2018-12-01']


In [55]:
np.mean(predp['linear_pre']), np.std(pred['linear_pre'])

(-1.4003233795089514, 0.9229976439890938)

In [56]:
np.mean(predg['linear_pre']), np.std(predg['linear_pre'])

(0.0, 0.0)

In [57]:
np.mean(predpo['linear_pre']), np.std(predpo['linear_pre'])

(0.0, 0.0)

In [58]:
np.mean(predpo['linear_post']), np.std(predpo['linear_post'])

(0.9499355310344024, 0.5460793238882227)

In [59]:
predp['linear'] = predp['linear_pre']

/home/poyraden/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [60]:
predpo['linear'] = predpo['linear_post']

/home/poyraden/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [61]:
predg['linear'] = predg['linear_pre']

/home/poyraden/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [62]:
frames = [predp, predg, predpo]

result = pd.concat(frames)

In [63]:
result

linear_pre  linear_post  post_const  pre_const  gap_const   enso  \
date                                                                        
1969-02   -2.791570     0.000000         0.0        1.0        0.0  0.849   
1969-03   -2.783904     0.000000         0.0        1.0        0.0  0.458   
1969-04   -2.775416     0.000000         0.0        1.0        0.0  0.622   
1969-05   -2.767203     0.000000         0.0        1.0        0.0  0.674   
1969-06   -2.758715     0.000000         0.0        1.0        0.0  0.801   
...             ...          ...         ...        ...        ...    ...   
2018-08   -0.000000     1.858217         1.0        0.0        0.0  0.132   
2018-09   -0.000000     1.866705         1.0        0.0        0.0  0.509   
2018-10   -0.000000     1.874919         1.0        0.0        0.0  0.468   
2018-11   -0.000000     1.883406         1.0        0.0        0.0  0.698   
2018-12   -0.000000     1.891620         1.0        0.0        0.0  0.698   

             qboA      qboB     solar       AOD    linear  
date                                                       
1969-02  1.132396  0.537626  0.672909  1.176370 -2.791570  
1969-03  1.322247  0.249722  1.087912  1.108205 -2.783904  
1969-04  1.437846 -0.268946  0.782558  1.043396 -2.775416  
1969-05  1.401092 -0.544063  0.612746  0.976292 -2.767203  
1969-06  1.306426 -0.793939  1.015524  0.907244 -2.758715  
...           ...       ...       ...       ...       ...  
2018-08  0.804669  1.743307 -1.143096 -0.458867  1.858217  
2018-09  1.185663  1.342924 -1.143096 -0.458867  1.866705  
2018-10  1.351891  0.933160 -1.143096 -0.458867  1.874919  
2018-11  1.646219  0.401344 -1.143096 -0.458867  1.883406  
2018-12  1.642771 -0.093206 -1.143096 -0.458867  1.891620  

[597 rows x 11 columns]

In [64]:
np.mean(result['linear']), np.std(result['linear'])

(-0.4245778334852421, 1.3194776544663636)

In [68]:
np.mean(result['qboA']), np.std(result['qboA'])

(-0.01245765253664847, 0.9968297569906235)

In [69]:
np.mean(result['qboB']), np.std(result['qboB'])

(0.000963603449571658, 1.00088526786013)

In [77]:
from pandas import DataFrame
from sklearn import linear_model
import statsmodels.api as sm

x = np.array([10, 20, 30, 40]).reshape((-1, 1))
y = np.array([8, 9, 10 ,11])

x

array([[10],
       [20],
       [30],
       [40]])

In [78]:

# with sklearn
regr = linear_model.LinearRegression()
regr.fit(x, y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Intercept: 
 7.0
Coefficients: 
 [0.1]


In [87]:
x = np.array([1, 2, 3, 4]).reshape((-1, 1))
y = np.array([8, 9, 10 ,11])
regr = linear_model.LinearRegression()
regr.fit(x, y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Intercept: 
 6.999999999999999
Coefficients: 
 [1.]


In [88]:
xn = (x - np.mean(x))/np.std(x)
print(xn)
regr = linear_model.LinearRegression()
regr.fit(xn, y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

[[-1.34164079]
 [-0.4472136 ]
 [ 0.4472136 ]
 [ 1.34164079]]
Intercept: 
 9.5
Coefficients: 
 [1.11803399]


In [96]:
x2 = np.array([-4,-3.5,-3,-2.5]).reshape((-1, 1))
regr = linear_model.LinearRegression()
regr.fit(x2, y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Intercept: 
 16.000000000000004
Coefficients: 
 [2.]


In [97]:
xn2 = (x2 - np.mean(x2))/np.std(x2)
print(xn2)
regr = linear_model.LinearRegression()
regr.fit(xn2, y)

print('Intercept: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

[[-1.34164079]
 [-0.4472136 ]
 [ 0.4472136 ]
 [ 1.34164079]]
Intercept: 
 9.5
Coefficients: 
 [1.11803399]


In [98]:
predictors = pd.read_csv('/home/poyraden/Analysis/MLR_Uccle/Files/Extended_ilt_alltrend_nor.csv')
predictors[0:3]

Unnamed: 0  linear_one   enso      qboA      qboB     solar       AOD
0    1969-01   -1.728962  0.670  1.269316  0.900528  0.594145  1.240826
1    1969-02   -1.723082  0.849  1.140860  0.542350  0.672909  1.176370
2    1969-03   -1.717771  0.458  1.331078  0.255986  1.087912  1.108205

In [99]:
predictors[-3:]

Unnamed: 0  linear_one   enso      qboA      qboB     solar       AOD
597    2018-10    1.717597  0.468  1.362195  0.935627 -1.143096 -0.458867
598    2018-11    1.723477  0.698  1.656915  0.406191 -1.143096 -0.458867
599    2018-12    1.729167  0.698  1.652505 -0.086264 -1.143096 -0.458867